# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 854781fffd83bfc4760a3b185071a0aeee7d96b95e06889da36cf7e3ac5155bfa52e5fa366ca5877bd1d16b633afd8224efaccf7ffde38ea9c95c4bbb8bbff1d

test:
  secret_key_base: 21b0041a78346822d342584faca0863c88d0256a2b8431c657ba1dbe63064f2207e7f4e13aa509b0ecec614389aed47acc095754fe3a9f6c879957bb121362df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
